apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: postgres-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: pg-service.app.svc.cluster.local
    database.port: "5432"
    # Find better way to store the configuration and secrets
    database.user: "postgres"
    database.password: "postgres"
    database.dbname: "postgres"
    database.server.name: "orders-db"
    topic.prefix: "orders"
    plugin.name: "pgoutput"
