
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kafka-app
  namespace: app
spec:
  selector:
    matchLabels:
      app: my-kafka-app
  template:
    metadata:
      labels:
        app: my-kafka-app
    spec:
      containers:
        - name: my-kafka-app
          image: ripplejb/simple-web-application-for-kafka:15.0.0
          ports:
            - containerPort: 80
          env:
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: pg-host
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: pg-username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: pg-password

---

apiVersion: v1
kind: Service
metadata:
  name: my-kafka-app
  namespace: app
spec:
  type: NodePort
  selector:
    app: my-kafka-app
  ports:
    - port: 8085
      targetPort: 80
      
