apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-volume
  labels:
    type: local
  namespace: app
spec:
  storageClassName: manual
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/postgres-data