apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pv-claim
  namespace: app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi