apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      volumes:
        - name: pg-storage
          persistentVolumeClaim:
            claimName: pg-pv-claim
      containers:
        - name: postgres
          image: postgres
          args: ["-c", "wal_level=logical"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: pg-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: pg-password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-storage
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: pg-service
  namespace: app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432